### ISSUE TITLE
something wrong in Healing.java

### ISSUE THREAD

**Issue by Lojincen** [yongjhih/HealingBrush#1]
in heal() method,
for (int i = 0; i < steps; i++) {
            healing.forEach_solve1(mask, dest2);
            healing.forEach_solve2(mask, dest1);
        }
It's stuck here.
NO ERROR，NO EXCEPTION.

**Comment by Lojincen** [comment]
I hit the “HEAL” button and there was no response.
And then I found out mRunScript do not run onPostExecute(string s).
Finally I found logic run in h.heal(healing, rs, image, output);

**Comment by Lojincen** [comment]
I print some log and found my app run More slowly than yours.WHY?

**Comment by jafu888** [comment]
printing uses compute resources and causes context switches.

**Comment by Lojincen** [comment]
same code in two project,BITMAP SIZE is different after decode*()
